version: '3.7'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"

